### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Ferkl** [grambas/football-data#1]
Hi,

if i try to install via composer (composer require grambas/football-data) in a fresh Laravel Instance I've got following Error:

[InvalidArgumentException]  
Could not find package grambas/football-data at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

What am I doing wrong?

**Comment by grambas** [comment]
Try to pull master branch with composer require grambas/football-data master

**Comment by Ferkl** [comment]
Hi,

thanks for your reply. 

If I installed a new laravel project (5.2) I had to add the following two lines to the composer.json to pull the master:

"minimum-stability": "dev",
"prefer-stable": true,

Now it works. Thx!

**Comment by grambas** [comment]
Created v1.0 branch. Now you can pull it without  "master"
