### ISSUE TITLE
Latest commit not on composer

### ISSUE THREAD

**Issue by robjbrain** [grambas/football-data#3]
I've just installed the package but unfortunately it doesn't have the latest commits and this completely breaks it, leaving random strings in the FootballData.php file:

```
    public function __construct(Client $client )
    {   
        $this->client = $client;
    }
<<<<<<< HEAD

    //COMPETITION/LEAGUE
    public function LeagueTable($id, $matchday="")
        {
        $leagueTable = $this->client->get("competitions/{$id}/leagueTable/?matchday={$matchday}")->getBody();
        return json_decode($leagueTable);
    }
```

I can see this was fixed in a commit here: https://github.com/grambas/football-data/commit/64cebb42947c39b9b733db23b5bd9ed176592827

But when doing composer install or composer update these commits are not included.

**Comment by grambas** [comment]
thanks, was issue in branching. Now i returned to dev-master branch and everything should work
